config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
resources :pictures,only:[:index,:new,:create,:edit,:update,:destroy]do
  collection do
    post :confirm
  end
 end
 
 root'top#index'
  get 'pictures' => 'pictures#index'
  
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
     end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
    validates :title,:content, presence: true
  belongs_to :user    

    mount_uploader :imageurl, ImageurlUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

 has_many :pictures

def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  
  def self.create_unique_string
    SecureRandom.uuid
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   before_action :configure_permitted_parameters, if: :devise_controller?
    PERMISSIBLE_ATTRIBUTES = %i(name)
    
   protected
   
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture,only: [:edit, :update, :destroy]
  
  def index
    @pictures =Picture.all
  end
  
  def new
    if params[:back]
      @picture = Picture.new(pictures_params)
    else
    @picture = Picture.new
    end
  end
  
  def confirm
    @picture = Picture.new(pictures_params)
    render :new if @picture.invalid?
  end
  
  def create
    @picture = Picture.new(pictures_params)
    @picture.user_id = current_user.id
    if @picture.save
    redirect_to pictures_path, notice: "投稿しました！"
    NoticeMailer.sendmail_picture(@picture).deliver
    else
    render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @picture.update(pictures_params)
      redirect_to pictures_path, notice: "ブログを更新しました！"
    else
      render 'edit'
    end
  end
  
  
def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"削除しました！"
  end
  
  private
   def pictures_params
     params.require(:picture).permit(:title, :content, :imageurl, :imageurl_cache)
   end
   def set_picture
     @picture = Picture.find(params[:id])
   end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
   def choose_new_or_edit
       if action_name == 'new'|| action_name == 'confirm'
          confirm_pictures_path
       elsif action_name == 'edit'
        picture_path
       end
    end
    
    def picture_img(user)
        return image_tag(user.imageurl,alt:user.name)if user.imageurl?
    end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nyanstagram</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <header>
        <%=link_to root_path do %>
        <img class="logo" src="<%= asset_path "logo.png" %>">
        <% end %>
        <ul>
          <li><%= link_to "トップページ",root_path %></li>
          <li><%= link_to "投稿一覧",pictures_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'マイページ', edit_user_registration_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
         <% else %>
            <li><%= link_to 'ログイン',new_user_session_path %></li>
            <li><%= link_to 'サインアップ', new_user_registration_path %></li>
         <% end %>
    　　</ul> 
    </header>
  
  <%= yield %>
  
  　<footer>
      <p>運営会社Yamaneko株式会社</p>
      <p>© 2015-2016 Copyright Yamaneko Corp.</p>
    　</footer>
    　
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture,url: choose_new_or_edit) do |f| %>
 <% if @picture.errors.any? %>
  <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      
      <ul>
          <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
  </div>
 <% end %>
 <%= f.label :タイトル %>
 <%= f.text_field :title,class: 'form-control' %>
 <br>
 <%= f.label :内容 %>
 <%= f.text_field :content,class: 'form-control' %>
 <br>
 <%= f.label :写真 %>
 <%= f.file_field :imageurl %>
 <%= f.hidden_field :imageurl_cache %>
 <%= f.submit'投稿', class:'btn btn-primary btn-block' %>
 <% end %>
 
 <%= link_to "投稿一覧に戻る",pictures_path %>  

app/views/pictures/confirm.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
      <h3>以下の内容で送信する</h3>
        <%= form_for(@picture) do |f| %>
        <%= f.hidden_field :title %>
        <%= f.hidden_field :content %>
        <%= f.hidden_field :imageurl %>
        <%= f.hidden_field :imageurl_cache %>
        
        <p>タイトル：<%= @picture.title %></p>
        <p>本文：<%= @picture.content %></p>
        <%= f.submit "登録",class:'btn btn-primary btn-block' %>
        <% end %>
        
        <%= form_for(@picture,url:new_picture_path,method:'get') do |f| %>
        <%= f.hidden_field :title %>
        <%= f.hidden_field :content %>
         <%= f.hidden_field :imageurl %>
        <%= f.hidden_field :imageurl_cache %>
        
        <%= f.submit "戻る",name: 'back',class:'btn btn-default btn-block' %>
        <% end %>
  </div>
 </div>
</div>

app/views/pictures/edit.html.erb
<div class="container">
 <div class="row">
     <div class="col-md-8 col-md-offset-2 col-sm-10 col-xs-12">
        <h1>編集する</h1>
        <%= render 'form' %>
     </div>
 </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-md-12 col-sm-10 col-xs-12">
        <p><%= notice %></p>
        
        <h1>投稿一覧</h1>
         <%= link_to "新規投稿する", new_picture_path, class: 'btn btn-default' %>
        <% @pictures.each do |picture| %>
        <div class="row">
             <p><%= picture.user.name %></p>
            <h4><strong><%= picture.title %></strong></h4>
            <p><%= picture.content %></p>
            <%= image_tag(picture.imageurl,:class => "image_url")%>
            <%= link_to "編集", edit_picture_path(picture.id), class:'btn btn-default btn-sm btn-success' %>
            <%= link_to "削除",picture_path(picture.id), method: :delete, 
            data:{confirm: '本当に削除していいですか？'},class: 'btn btn-default btn-sm btn btn-danger' %>
        </div>
        <% end %>
        
      </div>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">
 <div class="row">
     <div class="col-md-8 col-md-offset-2 col-sm-10 col-xs-12">
     <h1>投稿する</h1>
     <%= render 'form' %>
     </div>
 </div>
</div>

app/views/top/index.html.erb
<p><%= notice %></p>
    
    <div class="main">
       <p class="flash"><%= notice %><%= alert %></p>
       <img class="top" src= "<%= asset_path "top.png" %>">
    </div>
    
　